/**
 * Concise AGI opcode semantics derived from Peter Kelly's CC0 agi-re
 * behavioral specification: https://peterkelly.github.io/agi-re/spec/
 */

export const ACTION_HELP: Record<number, string> = {
  0x01: "Increment the variable, saturating at 255.",
  0x02: "Decrement the variable, saturating at 0.",
  0x03: "Store the immediate byte in the variable.",
  0x04: "Copy the source variable into the destination variable.",
  0x05: "Add the immediate byte to the variable, keeping the low 8 bits.",
  0x06: "Add the source variable to the destination variable, keeping the low 8 bits.",
  0x07: "Subtract the immediate byte from the variable, keeping the low 8 bits.",
  0x08: "Subtract the source variable from the destination variable, keeping the low 8 bits.",
  0x09: "Store the source value in the variable indexed by the index variable.",
  0x0a: "Read the variable indexed by the index variable into the destination variable.",
  0x0b: "Store the immediate byte in the variable indexed by the index variable.",
  0x0c: "Set the selected flag.",
  0x0d: "Clear the selected flag.",
  0x0e: "Toggle the selected flag.",
  0x0f: "Set the flag whose number is stored in the variable.",
  0x10: "Clear the flag whose number is stored in the variable.",
  0x11: "Toggle the flag whose number is stored in the variable.",
  0x12: "Switch rooms immediately: copy old v0 to v1, set v0 to the destination, preserve ego's view in v16, set f5, reset transient room state, and end logic flow. Entry v2=1/2/3/4 places ego at Y=167/X=0/Y=37/X=160-width, then clears v2. Build-specific immediate destination aliases apply only when the selected profile defines them.",
  0x13: "Switch to the room numbered by the variable, with the same initialization and logic-flow termination as new.room.",
  0x14: "Load and retain the selected logic resource.",
  0x15: "Load and retain the logic resource numbered by the variable.",
  0x16: "Invoke the selected logic with its own message table, then restore the caller; a deliberate callee abort propagates.",
  0x17: "Invoke the logic numbered by the variable with call semantics; a deliberate callee abort propagates.",
  0x18: "Load the picture resource numbered by the variable.",
  0x19: "Clear the logical picture surfaces and decode the loaded picture numbered by the variable; show.pic makes it visible.",
  0x1a: "Present the prepared picture and mark it shown. Profiles 2.089, 2.230, and 2.272 retain f15 and an active text window; later profiles clear f15 and close the window.",
  0x1b: "Discard the loaded picture numbered by the variable and all pictures retained after it.",
  0x1c: "Overlay the loaded picture numbered by the variable without clearing logical surfaces; show.pic is still required.",
  0x1d: "Show priority/control values temporarily, wait for input, then restore the normal picture.",
  0x1e: "Load the selected view resource.",
  0x1f: "Load the view resource numbered by the variable.",
  0x20: "Discard the selected loaded view and all views retained after it.",
  0x21: "Initialize an object for updates and automatic cel cycling if needed, clearing its direction and motion/cycling modes.",
  0x22: "Remove active and update-eligible state from every persistent object.",
  0x23: "Activate an object with a selected cel, snapshot its cel and position, and add it to update/draw processing.",
  0x24: "Deactivate the object and remove it from update/draw processing.",
  0x25: "Set the object's current and previous position to immediate X and baseline Y.",
  0x26: "Set the object's current and previous position from the X and baseline-Y variables.",
  0x27: "Store the object's current X and baseline Y in the destination variables.",
  0x28: "Add signed 8-bit variable deltas to the object's position, clamp negative underflow to zero, and run placement.",
  0x29: "Bind the loaded immediate view to the object and select its default loop and cel.",
  0x2a: "Bind the loaded view numbered by the variable to the object.",
  0x2b: "Select the object's immediate loop and that loop's default cel.",
  0x2c: "Select the object's loop from the variable.",
  0x2d: "Disable automatic direction-based loop selection for the object.",
  0x2e: "Enable automatic direction-based loop selection for the object.",
  0x2f: "Select an immediate cel, refresh dimensions, clamp placement if needed, and remove the one-cycle animation delay.",
  0x30: "Select the cel numbered by the variable, refresh dimensions, clamp placement if needed, and remove the animation delay.",
  0x31: "Store the selected loop's highest valid cel index; profile 2.230 reads the cel count from the header's low nibble.",
  0x32: "Store the object's selected cel index in the destination variable.",
  0x33: "Store the object's selected loop index in the destination variable.",
  0x34: "Store the object's selected view number in the destination variable.",
  0x35: "Store the selected view's loop count in the destination variable.",
  0x36: "Give the object the immediate fixed priority.",
  0x37: "Give the object the fixed priority stored in the variable.",
  0x38: "Release fixed priority so the object's priority follows its baseline Y.",
  0x39: "Store the object's current priority in the destination variable.",
  0x3a: "Move an active object to the earlier-drawn update partition.",
  0x3b: "Move an active object to the later-drawn update partition.",
  0x3c: "Flush, rebuild, draw, and refresh every object update list; the object operand does not narrow the refresh.",
  0x3d: "Exempt the object from the horizon clamp.",
  0x3e: "Re-enable the horizon clamp for the object.",
  0x3f: "Set the horizon; nonexempt objects at or above it are placed at least one row below it.",
  0x40: "Require the object's final footprint class state to have flag 0 set (the on-water gate).",
  0x41: "Require the object's final footprint class state to have flag 0 clear (the on-land gate).",
  0x42: "Clear both class-2 and class-3 footprint rejection options for the object.",
  0x43: "Exempt the object from object-object crossing and collision tests.",
  0x44: "Re-enable object-object crossing and collision tests for the object.",
  0x45: "Store center-X plus baseline-Y Manhattan distance, or 255 if either object is inactive. Profiles 2.089, 2.230, and 2.272 keep the low byte on overflow; later profiles cap at 254.",
  0x46: "Disable automatic cel cycling while retaining the current cel.",
  0x47: "Enable automatic cel cycling.",
  0x48: "Select forward cel cycling, wrapping after the last cel.",
  0x49: "Clear the completion flag, cycle forward to the last cel after an initial callback delay, then stop and set the flag.",
  0x4a: "Select backward cel cycling, wrapping before cel 0.",
  0x4b: "Clear the completion flag, cycle backward to cel 0 after an initial callback delay, then stop and set the flag.",
  0x4c: "Set both the object's cel-cycle reload interval and current countdown from the variable.",
  0x4d: "Clear direction; profiles 2.089 and 2.230 leave autonomous motion active, while later profiles clear it. For object 0, also clear v6 and select object-to-v6 coupling.",
  0x4e: "Keep direction; profiles 2.089 and 2.230 also leave autonomous motion unchanged, while later profiles clear it. For object 0, clear v6 and select v6-to-object coupling; the early profiles also clear remembered navigation input.",
  0x4f: "Set the object's movement step size from the variable.",
  0x50: "Set the object's movement/update cadence countdown from the variable and restart its cadence phase.",
  0x51: "Move toward immediate X/Y, temporarily replacing step size when the override is nonzero. Clear the flag now; restore step and set it when both target deltas lie strictly within +/-step or a corresponding reachable screen boundary is reached. Profiles 2.089, 2.230, and 2.272 defer the first calculation to the next eligible update.",
  0x52: "Move toward variable-selected X/Y with the same completion and early-profile deferral rules; a nonzero step variable temporarily replaces step size, and zero preserves it.",
  0x53: "Move toward object 0 using centers and baselines until within the threshold, then stop and set the completion flag.",
  0x54: "Begin autonomous random-direction motion.",
  0x55: "Stop autonomous motion without clearing the object's current direction.",
  0x56: "Set the object's direction from the variable: 0 stationary, then 1..8 clockwise from up through up-left.",
  0x57: "Store the object's current direction in the destination variable.",
  0x58: "Ignore movement-rectangle transitions and allow control value 1 in the object's footprint scan.",
  0x59: "Observe movement-rectangle transitions and reject control value 1 in the object's footprint scan.",
  0x5a: "Enable the global movement rectangle; inside membership uses strict comparison against all four immediate bounds.",
  0x5b: "Disable the global movement rectangle.",
  0x5c: "Set the immediate inventory item's location to 0xff (carried).",
  0x5d: "Set the variable-selected inventory item's location to 0xff (carried).",
  0x5e: "Set the immediate inventory item's location to 0.",
  0x5f: "Set the immediate inventory item's location from the location variable.",
  0x60: "Set the variable-selected inventory item's location from the location variable.",
  0x61: "Store the variable-selected inventory item's location in the destination variable.",
  0x62: "Load the selected sound resource.",
  0x63: "Stop prior sound, clear the completion flag, and play the loaded sound; set the flag when playback completes or is stopped.",
  0x64: "Stop active sound and set its remembered completion flag.",
  0x65: "Show the current logic's message modally and wait for acknowledgement.",
  0x66: "Show the message numbered by the variable modally.",
  0x67: "Expand substitutions in the message and display it at the immediate row and column.",
  0x68: "Display the variable-selected message at variable-selected row and column with substitutions expanded.",
  0x69: "Clear full-width text rows from top through bottom, inclusively, using the selected attribute.",
  0x6a: "Enter alternate full-screen text mode, fill its surface, and suppress object graphics updates.",
  0x6b: "Leave alternate text mode, restore graphics updates, and redraw status and input areas.",
  0x6c: "Use the message's first byte as the input prompt marker; an empty message hides the marker.",
  0x6d: "Set foreground/background attributes for text windows and alternate text mode.",
  0x6e: "Shake the visible display for the requested count with paced offsets.",
  0x6f: "Configure the display base, input, and status rows.",
  0x70: "Enable and redraw the status line at its configured row.",
  0x71: "Disable and clear the status line at its configured row.",
  0x72: "Copy the message into the selected 40-byte string slot.",
  0x73: "Clear the string slot, show the prompt, edit input at the optional row/column, and store at most min(maximum + 1, 40) bytes.",
  0x74: "Copy the selected normalized parsed word into the string slot.",
  0x75: "Clear prior parser-match state and parse the string slot; invalid slots do nothing. Profiles 2.089, 2.230, and 2.272 expose slots 0..5; later profiles expose 0..11.",
  0x76: "Prompt for up to four decimal characters and store the accepted number's low 8 bits in the destination variable.",
  0x77: "Disable and clear the input line.",
  0x78: "Enable and redraw the input line.",
  0x79: "Map the little-endian key word to a controller() status. Most promoted profiles allow 39 mappings; profile 3.002.149 allows 49.",
  0x7a: "Draw a loaded view/loop/cel into persistent picture state at X and baseline Y with the supplied priority and control/margin, recording restore replay.",
  0x7b: "Variable-selected form of add.to.pic for all seven operands.",
  0x7c: "Show items whose location is 0xff. Interactive mode stores the choice in v25 or 0xff on cancel; profiles 2.089, 2.230, and 2.272, or a disabled interaction flag, make the list acknowledgement-only.",
  0x7d: "Open the modal save selector; cancel or handled failure continues, and success saves state then continues.",
  0x7e: "Open the modal restore selector; cancel/failure continues, while success replaces runtime state and aborts the current continuation.",
  0x7f: "No operation.",
  0x80: "Request restart; cancellation continues, while acceptance resets state, sets the restarted flag, and aborts current logic. Profile 2.411 always confirms; other promoted profiles skip confirmation when f16 is set.",
  0x81: "Temporarily load and preview the view with associated text, wait for acknowledgement, then discard only if this action loaded it.",
  0x82: "Store a pseudorandom value in the inclusive immediate range low..high.",
  0x83: "Select object-0-to-v6 direction coupling.",
  0x84: "Select v6-to-object-0 direction coupling and stop object 0's autonomous motion.",
  0x85: "Display modal diagnostics for the object numbered by the variable: position, size, priority, and step size.",
  0x86: "Quit semantics vary by profile: early profiles terminate with no operand; later profiles quit immediately for selector 1 and otherwise ask for confirmation.",
  0x87: "Display profile-dependent heap and resource diagnostics modally.",
  0x88: "Stop sound, show the fixed pause message modally, then resume after acknowledgement.",
  0x89: "Redraw the enabled input line from the accepted input buffer.",
  0x8a: "Erase all visible input-line characters.",
  0x8b: "Run interactive joystick centering and range calibration when a joystick exists.",
  0x8c: "Toggle a supported alternate display mode and rebuild it from retained replay events; this is outside the full-EGA target.",
  0x8d: "Display the interpreter name and version modally.",
  0x8e: "Set resource replay-pair capacity, reset the replay sequence, and refresh object update lists.",
  0x8f: "Set the game signature from up to seven message bytes and terminate on mismatch; profile 2.936 expects SQ2 and 3.002.149 accepts GR.",
  0x90: "Append current room, input line, and expanded message to LOGFILE; an open failure returns normally.",
  0x91: "Save the following bytecode position as this logic's resume point for later cycles.",
  0x92: "Reset this logic's future resume point to bytecode entry; current execution continues.",
  0x93: "Set the object's immediate position, mark it newly positioned, and run placement without directly replacing its previous-position snapshot.",
  0x94: "Set the object's position from variables, mark it newly positioned, and run placement without directly replacing its previous-position snapshot.",
  0x95: "If tracing is inactive and f10 is set, enable the trace window; if already active, consume one extra byte and return.",
  0x96: "Configure trace logic, row offset, and window height, clamping height to at least 2.",
  0x97: "Show an immediate message modally with temporary row, column, and width; zero width means 30, then defaults are restored.",
  0x98: "Show the variable-selected message modally with temporary row, column, and width; zero width means 30, then restore defaults.",
  0x99: "Discard the loaded view numbered by the variable and every view retained after it.",
  0x9a: "Clear the inclusive text-cell rectangle using the selected attribute; EGA cells are 4 by 8 logical pixels.",
  0x9b: "Consume two ignored bytes and otherwise do nothing.",
  0x9c: "Append a top-level menu heading from the message unless menus are finalized; profile 2.272 accepts this as a no-op.",
  0x9d: "Append an enabled menu item with the given ID unless finalized; profile 2.272 accepts this as a no-op.",
  0x9e: "Finalize menu construction and establish initial selection; profile 2.272 accepts this as a no-op.",
  0x9f: "Enable every menu item with the matching ID; profile 2.272 accepts this as a no-op.",
  0xa0: "Disable every menu item with the matching ID; profile 2.272 accepts this as a no-op.",
  0xa1: "If f14 is set, request modal menu interaction on the input cycle.",
  0xa2: "Preview the view numbered by the variable using show.obj semantics.",
  0xa3: "Enable the fixed input-width override with a 36-character starting cap where supported; profile 3.002.149 does nothing.",
  0xa4: "Disable the fixed input-width override where supported; profile 3.002.149 does nothing.",
  0xa5: "Multiply the variable by the immediate byte, keeping the low 8 bits.",
  0xa6: "Multiply the destination variable by the source variable, keeping the low 8 bits.",
  0xa7: "Divide the variable by the immediate byte and store the unsigned quotient; zero divisors are invalid bytecode.",
  0xa8: "Divide the destination variable by the divisor variable and store the unsigned quotient; zero divisors are invalid.",
  0xa9: "Close and restore an active text window, if any. Profiles with a fixed input-width override also clear it; profile 3.002.149 has no such override.",
  0xaa: "Copy up to 31 bytes of the current save-selector description/path buffer into the string slot.",
  0xab: "Save the current resource replay-pair count as a rollback point.",
  0xac: "Restore the saved replay-pair count and place the next replay write after the restored final pair.",
  0xad: "Open the key-release event gate: increment it modulo 256 in V2/3.002.086, or set it to 1 in later V3 profiles.",
  0xae: "Rebuild baseline priorities: rows below the horizon argument map to 4, then rise from 5 toward 15 over the 168-row picture.",
  0xaf: "Runtime no-op consuming no operand, although scanner metadata assigns it a one-byte operand length.",
  0xb0: "V3 no-op: profile 3.002.086 consumes one ignored byte; profiles 3.002.102 and 3.002.149 consume none.",
  0xb1: "Set the V3 menu gate: zero blocks modal entry and nonzero permits it.",
  0xb2: "No operation in profiles 3.002.102 and 3.002.149.",
  0xb3: "Consume four ignored bytes and otherwise do nothing in later V3 profiles.",
  0xb4: "Consume two variable-index operands and otherwise do nothing in later V3 profiles.",
  0xb5: "Clear the key-release event gate in later V3 profiles.",
};

export const CONDITION_HELP: Record<number, string> = {
  0x00: "Always false.",
  0x01: "True when the unsigned variable equals the immediate byte.",
  0x02: "True when the two unsigned variable values are equal.",
  0x03: "True when the unsigned variable is less than the immediate byte.",
  0x04: "True when the first unsigned variable is less than the second.",
  0x05: "True when the unsigned variable is greater than the immediate byte.",
  0x06: "True when the first unsigned variable is greater than the second.",
  0x07: "True when the selected flag is set.",
  0x08: "True when the flag whose number is stored in the variable is set.",
  0x09: "True when the inventory item's location byte is exactly 0xff (carried).",
  0x0a: "True when the inventory item's location byte equals the unsigned variable value.",
  0x0b: "True when the object's left X and baseline Y are within the inclusive rectangle.",
  0x0c: "True when the selected mapped-event status byte is nonzero.",
  0x0d: "True when a raw key is available or v19 already holds one; captures a new nonzero low key byte in v19 and discards non-key events while searching.",
  0x0e: "Can match only when f2 is set, the parser count/error position is nonzero, and f4 is clear. Word ID 1 matches one word. Profile 2.089 requires an exact count and treats 9999 literally; later profiles use 9999 to accept the remaining tail, including a terminator-only recorded unknown token. Success sets f4.",
  0x0f: "Remove spaces, tabs, periods, commas, semicolons, colons, apostrophes, exclamation marks, and hyphens from each string, lowercase ASCII A..Z, then compare exactly.",
  0x10: "True when both ends of the object's X..X+width-1 span and its baseline Y are within the inclusive rectangle.",
  0x11: "True when the object's X+floor(width/2) center and baseline Y are within the inclusive rectangle.",
  0x12: "True when the object's X+width-1 right edge and baseline Y are within the inclusive rectangle.",
};
