/**
 * Sprite sheet -> AGI VIEW pipeline: deterministic quantisation, grid cutting
 * and cel packing for sprites produced by an image model.
 *
 * Authority stays in code: the model produces one
 * flat bitmap under strict constraints and this module does every irreversible
 * decision — palette, transparency, trimming, downsampling, loop layout — so
 * the result is reproducible and reviewable byte for byte.
 *
 * ## Prompt constraints for the image model
 *
 * The authoring tool must state all of these; each one removes a class of
 * failure this pipeline cannot repair:
 *
 * - **Key frames in a single row per animation, left to right**, evenly
 *   spaced, one character per cell, same character size and same ground
 *   contact line in every cell. `cutGrid` splits on an exact grid; uneven
 *   spacing shears every frame.
 * - **Flat key-colour background** (one saturated colour that does not appear
 *   on the character, e.g. pure magenta `#ff00ff`), filling the border of the
 *   sheet. `quantizeToEga` detects the key from the border ring; a gradient,
 *   drop shadow or vignette background becomes opaque pixels.
 * - **Side view (or straight-on for front/back walk cycles), full body,
 *   feet at the bottom of the cell.** The bottom row of the trimmed art is the
 *   AGI baseline; a floating character walks above the ground.
 * - **No anti-aliasing, no soft edges, no gradients, no outlines that fade.**
 *   Hard-edged flat colour only: nearest-colour quantisation with no dithering
 *   turns soft edges into ragged fringes of the wrong hue.
 * - **A limited flat palette, ideally already the EGA 16.** Every colour snaps
 *   to the nearest EGA entry; nearby shades collapse into one index.
 * - **No text, no frame numbers, no borders, no drop shadow on the ground.**
 * - Draw the character facing **right** for the walk cycle; the mirrored loop
 *   (facing left) is generated by the interpreter from the same cel data.
 *
 * ## Aspect rule
 *
 * The AGI logical picture surface is 160x168 (src/types.ts) but is displayed
 * with each logical pixel two raster columns wide and one raster row tall: the
 * spec's brush "Plot geometry" (agi-re, "Picture Resources and Rendering")
 * doubles logical X into a `horizontal_limit` of `320` while Y is clamped
 * against `167` unscaled. A logical pixel is therefore twice as wide as it is
 * tall. A sprite sheet drawn with square pixels must be squeezed horizontally
 * by that factor when it is resampled: for a target cel height `H`,
 *
 *     celWidth = round(frameWidth * (H / frameHeight) / pixelAspect)
 *
 * with `pixelAspect` defaulting to 2. A 64x64 square-pixel frame downsampled
 * to a 32-pixel-tall ego cel becomes 16x32 logical pixels, which redisplays as
 * 32x32 raster pixels — the original proportions.
 *
 * Zero dependencies; runs in browser, worker and Node.
 */

import { buildView, type BuildCelInput, type BuildLoopInput } from "./view.ts";

/** The authentic 16-colour EGA palette, RGB, indexed by colour nibble. */
export const EGA_PALETTE: readonly (readonly [number, number, number])[] = [
  [0x00, 0x00, 0x00],
  [0x00, 0x00, 0xaa],
  [0x00, 0xaa, 0x00],
  [0x00, 0xaa, 0xaa],
  [0xaa, 0x00, 0x00],
  [0xaa, 0x00, 0xaa],
  [0xaa, 0x55, 0x00],
  [0xaa, 0xaa, 0xaa],
  [0x55, 0x55, 0x55],
  [0x55, 0x55, 0xff],
  [0x55, 0xff, 0x55],
  [0x55, 0xff, 0xff],
  [0xff, 0x55, 0x55],
  [0xff, 0x55, 0xff],
  [0xff, 0xff, 0x55],
  [0xff, 0xff, 0xff],
];

/**
 * Nearest EGA colour index for an RGB triple, by weighted squared distance
 * (2,4,3 on R,G,B — a cheap stand-in for luminance sensitivity). Ties resolve
 * to the lower index, so the mapping is total and deterministic.
 */
export function nearestEgaIndex(r: number, g: number, b: number): number {
  let best = 0;
  let bestDistance = Infinity;
  for (let i = 0; i < EGA_PALETTE.length; i++) {
    const [pr, pg, pb] = EGA_PALETTE[i]!;
    const dr = r - pr;
    const dg = g - pg;
    const db = b - pb;
    const distance = 2 * dr * dr + 4 * dg * dg + 3 * db * db;
    if (distance < bestDistance) {
      bestDistance = distance;
      best = i;
    }
  }
  return best;
}

export interface QuantizeOptions {
  /**
   * Explicit background key colour as RGB. It is quantised to EGA first, so
   * `#ff00ff` and `#f70df3` select the same key. `null` disables key-colour
   * transparency, leaving alpha as the only source.
   */
  keyColor?: readonly [number, number, number] | null | undefined;
  /** Alpha below this value is transparent. Default 128. */
  alphaThreshold?: number | undefined;
}

export interface EgaSheet {
  readonly width: number;
  readonly height: number;
  /**
   * One EGA colour nibble per pixel, row-major. Transparent pixels hold
   * `keyIndex` (or 0 when there is none); `mask` is the authority on which
   * pixels are transparent, because the cel's transparent colour is not
   * chosen until the cel is packed.
   */
  readonly pixels: Uint8Array;
  /** 1 = opaque, 0 = transparent. Row-major, same length as `pixels`. */
  readonly mask: Uint8Array;
  /** EGA index of the detected or supplied key colour, or null if none. */
  readonly keyIndex: number | null;
}

/**
 * Quantise an RGBA bitmap to EGA nibbles with a transparency mask.
 *
 * A pixel is transparent when its alpha is below the threshold, or when it
 * quantises to the key colour. The key colour defaults to the most common EGA
 * index along the one-pixel border ring of the sheet (ties resolve to the
 * lower index); a sheet whose border is fully alpha-transparent has no key.
 * No dithering: every pixel maps independently to its nearest EGA entry.
 */
export function quantizeToEga(
  rgba: Uint8Array | Uint8ClampedArray,
  width: number,
  height: number,
  opts?: QuantizeOptions,
): EgaSheet {
  if (!Number.isInteger(width) || !Number.isInteger(height) || width < 1 || height < 1) {
    throw new RangeError(`sheet dimensions must be positive integers (got ${width}x${height})`);
  }
  if (rgba.length !== width * height * 4) {
    throw new RangeError(
      `rgba length ${rgba.length} does not match ${width}x${height}x4 = ${width * height * 4}`,
    );
  }
  const alphaThreshold = opts?.alphaThreshold ?? 128;

  const count = width * height;
  const pixels = new Uint8Array(count);
  const opaque = new Uint8Array(count);
  for (let i = 0; i < count; i++) {
    const o = i * 4;
    opaque[i] = rgba[o + 3]! >= alphaThreshold ? 1 : 0;
    pixels[i] = nearestEgaIndex(rgba[o]!, rgba[o + 1]!, rgba[o + 2]!);
  }

  let keyIndex: number | null;
  if (opts && "keyColor" in opts && opts.keyColor !== undefined) {
    const key = opts.keyColor;
    keyIndex = key === null ? null : nearestEgaIndex(key[0], key[1], key[2]);
  } else {
    keyIndex = detectBorderKey(pixels, opaque, width, height);
  }

  const mask = new Uint8Array(count);
  for (let i = 0; i < count; i++) {
    mask[i] = opaque[i] === 1 && pixels[i] !== keyIndex ? 1 : 0;
    if (mask[i] === 0) pixels[i] = keyIndex ?? 0;
  }
  return { width, height, pixels, mask, keyIndex };
}

function detectBorderKey(
  pixels: Uint8Array,
  opaque: Uint8Array,
  width: number,
  height: number,
): number | null {
  const histogram = new Array<number>(16).fill(0);
  let seen = 0;
  const tally = (i: number): void => {
    if (opaque[i] === 1) {
      histogram[pixels[i]!]!++;
      seen++;
    }
  };
  for (let x = 0; x < width; x++) {
    tally(x);
    if (height > 1) tally((height - 1) * width + x);
  }
  for (let y = 1; y < height - 1; y++) {
    tally(y * width);
    if (width > 1) tally(y * width + width - 1);
  }
  if (seen === 0) return null;
  let best = 0;
  for (let i = 1; i < 16; i++) {
    if (histogram[i]! > histogram[best]!) best = i;
  }
  return best;
}

export interface SheetFrame {
  readonly width: number;
  readonly height: number;
  /** EGA nibble per pixel, row-major. Only meaningful where `mask` is 1. */
  readonly pixels: Uint8Array;
  /** 1 = opaque, 0 = transparent. */
  readonly mask: Uint8Array;
}

export interface CutGridOptions {
  /**
   * Trim the transparent margin shared by every frame. The bounding box is the
   * union of all frames' opaque pixels, so each frame keeps its position
   * inside the common box and the bottom row (the AGI baseline) stays aligned
   * across the whole sheet. Default true.
   */
  trim?: boolean | undefined;
  /**
   * Nearest-neighbour downsample so every frame is this many logical pixels
   * tall (e.g. 32 for an ego). Width follows the aspect rule below. Omit to
   * keep the source resolution.
   */
  targetHeight?: number | undefined;
  /**
   * Source pixels per logical pixel horizontally. Default 2: an AGI logical
   * pixel is two raster columns wide and one row tall (see the aspect rule in
   * this file's header), so a square-pixel sheet is squeezed by 2 in X.
   */
  pixelAspect?: number | undefined;
}

/**
 * Split a quantised sheet into `columns * rows` equally sized frames, in
 * reading order (left to right, then top to bottom), then trim and optionally
 * downsample them as one group.
 */
export function cutGrid(
  sheet: EgaSheet,
  columns: number,
  rows: number,
  opts?: CutGridOptions,
): SheetFrame[] {
  if (!Number.isInteger(columns) || !Number.isInteger(rows) || columns < 1 || rows < 1) {
    throw new RangeError(`columns and rows must be positive integers (got ${columns}x${rows})`);
  }
  if (sheet.width % columns !== 0 || sheet.height % rows !== 0) {
    throw new RangeError(
      `sheet ${sheet.width}x${sheet.height} does not divide evenly into ${columns}x${rows} frames`,
    );
  }
  const cellWidth = sheet.width / columns;
  const cellHeight = sheet.height / rows;

  // Union bounding box of opaque pixels in frame-local coordinates.
  let left = cellWidth;
  let right = -1;
  let top = cellHeight;
  let bottom = -1;
  if (opts?.trim !== false) {
    for (let row = 0; row < rows; row++) {
      for (let col = 0; col < columns; col++) {
        const originX = col * cellWidth;
        const originY = row * cellHeight;
        for (let y = 0; y < cellHeight; y++) {
          for (let x = 0; x < cellWidth; x++) {
            if (sheet.mask[(originY + y) * sheet.width + originX + x] !== 1) continue;
            if (x < left) left = x;
            if (x > right) right = x;
            if (y < top) top = y;
            if (y > bottom) bottom = y;
          }
        }
      }
    }
    if (right < 0) {
      throw new RangeError("sheet has no opaque pixels: nothing to cut");
    }
  } else {
    left = 0;
    top = 0;
    right = cellWidth - 1;
    bottom = cellHeight - 1;
  }

  const boxWidth = right - left + 1;
  const boxHeight = bottom - top + 1;

  let outWidth = boxWidth;
  let outHeight = boxHeight;
  if (opts?.targetHeight !== undefined) {
    const targetHeight = opts.targetHeight;
    if (!Number.isInteger(targetHeight) || targetHeight < 1) {
      throw new RangeError(`targetHeight must be a positive integer (got ${targetHeight})`);
    }
    const pixelAspect = opts.pixelAspect ?? 2;
    if (!(pixelAspect > 0)) {
      throw new RangeError(`pixelAspect must be positive (got ${pixelAspect})`);
    }
    outHeight = targetHeight;
    outWidth = Math.max(1, Math.round((boxWidth * (targetHeight / boxHeight)) / pixelAspect));
  }

  const frames: SheetFrame[] = [];
  for (let row = 0; row < rows; row++) {
    for (let col = 0; col < columns; col++) {
      const originX = col * cellWidth + left;
      const originY = row * cellHeight + top;
      const pixels = new Uint8Array(outWidth * outHeight);
      const mask = new Uint8Array(outWidth * outHeight);
      for (let y = 0; y < outHeight; y++) {
        // Nearest neighbour: sample the source pixel under the centre of the
        // destination pixel. Identical for every frame, so the baseline holds.
        const sy = outHeight === boxHeight ? y : Math.floor(((y + 0.5) * boxHeight) / outHeight);
        for (let x = 0; x < outWidth; x++) {
          const sx = outWidth === boxWidth ? x : Math.floor(((x + 0.5) * boxWidth) / outWidth);
          const src = (originY + sy) * sheet.width + originX + sx;
          const dst = y * outWidth + x;
          pixels[dst] = sheet.pixels[src]!;
          mask[dst] = sheet.mask[src]!;
        }
      }
      frames.push({ width: outWidth, height: outHeight, pixels, mask });
    }
  }
  return frames;
}

export interface SheetLoopLayout {
  /** Frame indices, in cel order. Omit together with `mirrorOf` is an error. */
  frames?: readonly number[] | undefined;
  /**
   * Reuse a preceding loop's cels mirrored (the spec's stateful per-cel
   * orientation, "View Resources and Cel Drawing"). Ignored when `frames` is
   * given.
   */
  mirrorOf?: number | undefined;
}

export interface SheetViewLayout {
  readonly loops: readonly SheetLoopLayout[];
  /** Optional embedded display string. */
  description?: string | undefined;
  /**
   * Transparent colour to prefer for every cel, when the cel's opaque pixels
   * leave it free. Defaults to the sheet's detected key index if supplied,
   * else the lowest free index.
   */
  preferTransparent?: number | undefined;
}

/**
 * Pack cut frames into a VIEW payload.
 *
 * Each cel's transparent colour is chosen per the spec's cel control byte (low
 * nibble): the preferred index if no opaque pixel in that cel uses it, else
 * the lowest index that is free. A cel using all 16 colours has no encodable
 * transparent colour and is rejected rather than silently recoloured.
 */
export function buildViewFromSheet(
  frames: readonly SheetFrame[],
  layout: SheetViewLayout,
): Uint8Array {
  const loops: BuildLoopInput[] = [];
  for (let loopIndex = 0; loopIndex < layout.loops.length; loopIndex++) {
    const loop = layout.loops[loopIndex]!;
    if (loop.frames === undefined || loop.frames.length === 0) {
      if (loop.mirrorOf === undefined) {
        throw new RangeError(`loop ${loopIndex} has neither frames nor mirrorOf`);
      }
      loops.push({ mirrorLoop: loop.mirrorOf });
      continue;
    }
    const cels: BuildCelInput[] = [];
    for (const frameIndex of loop.frames) {
      const frame = frames[frameIndex];
      if (frame === undefined) {
        throw new RangeError(
          `loop ${loopIndex} references frame ${frameIndex}, but only ${frames.length} were cut`,
        );
      }
      cels.push(celFromFrame(frame, layout.preferTransparent));
    }
    loops.push({ cels });
  }
  return buildView(
    layout.description === undefined ? { loops } : { loops, description: layout.description },
  );
}

function celFromFrame(frame: SheetFrame, prefer: number | undefined): BuildCelInput {
  const used = new Array<boolean>(16).fill(false);
  for (let i = 0; i < frame.mask.length; i++) {
    if (frame.mask[i] === 1) used[frame.pixels[i]! & 0x0f] = true;
  }
  let transparentColor = -1;
  if (prefer !== undefined && prefer >= 0 && prefer <= 15 && !used[prefer]) {
    transparentColor = prefer;
  } else {
    for (let i = 0; i < 16; i++) {
      if (!used[i]) {
        transparentColor = i;
        break;
      }
    }
  }
  if (transparentColor < 0) {
    throw new RangeError("cel uses all 16 EGA colours: no colour is left to encode transparency");
  }
  const pixels = new Uint8Array(frame.pixels.length);
  for (let i = 0; i < pixels.length; i++) {
    pixels[i] = frame.mask[i] === 1 ? frame.pixels[i]! & 0x0f : transparentColor;
  }
  return { width: frame.width, height: frame.height, transparentColor, pixels };
}
