import { chromium } from "playwright";
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1063, height: 815 } });
await page.goto("http://localhost:5199/#create-adventure");
await page.waitForSelector('[data-testid="local-create-kind-starter"]', { timeout: 30000 });
await page.click('[data-testid="local-create-kind-starter"]');
await page.click('button:has-text("Start building")');
await page.waitForSelector('[data-testid="part-room:1:picture:1"]', { timeout: 30000 });
await page.click('[data-testid="part-room:1:picture:1"]');
await page.waitForSelector('[data-testid="room-studio"]', { timeout: 15000 });
await page.getByRole("button", { name: "Stacked", exact: true }).click();
await page.waitForTimeout(600);
await page.screenshot({ path: "../logs/rc4-g1-shots/g1-after-stacked-1063x815.png" });
const d = await page.evaluate(() => {
  const s = document.querySelector('[data-testid="room-studio"]');
  const t = document.querySelector(".studio__side .scene-list [role=tree]");
  return { studioH: s.clientHeight, scrollH: s.scrollHeight, treeH: t?.getBoundingClientRect().height };
});
console.log(d);
await b.close();
